:markup-in-source: verbatim,attributes,quotes

== Run the Jenkins Pipeline

In this section of the lab you will examine the Jenkins Pipeline and - if you want to - execute the pipeline.

. Open your web browser and navigate to Jenkins at %jenkins_url%.
. Click the blue *Login to OpenShift* button to log into Jenkins. ... Use %ocp_username% and your OpenTLC password as credentials.
.. Accept the request for permissions
. On the Jenkins Overview page you will see a folder, *jenkins*. Open the folder by clicking on the name.
. You will see a Jenkins task *jenkins/petclinic-pipeline*. Open the task by clicking on it.
+
[NOTE]
Note that you do not have permissions to start the Jenkins task from the Jenkins User Interface. This is because you only have


. Launch task ...

. Use the following commands:
+
[source,options="nowrap",subs="{markup-in-source}"]
----
$ *ansible localhost -m lineinfile -a 'path=$HOME/.bashrc regexp="^export OCP_RELEASE" line="export OCP_RELEASE=4.3.1"'*

$ *source $HOME/.bashrc*
----


=== Summary

You have completed the following:

* Deployed ...
* Created ...
* Customized ...
