:markup-in-source: verbatim,attributes,quotes

// Title comes from the workshop.yaml
// == Test Tekton Tasks

Before running our pipeline, you can test each single task by creating a *TaskRun*, another Tekton object that let us execute just one task rather then the entire pipeline. This is a really convenient way to test that your tasks are working properly before executing the entire pipeline.

The *TaskRun* can be created from a YAML file, or with `tkn` CLI.

== Pipeline Service Account

OpenShift Pipelines provides a service account, `pipeline`, which gets created in each project by the pipeline operator. The service account is used to run pipelines and tasks. Therefore it needs to have the right permission to access private repositories and private registries as well as all projects that a task or pipeline needs to access.

=== Enabling access to a private Source Code Repository

As a project administrator, you can grant the right permission to the `pipeline` service account in order allow the `git-clone` ClusterTask access to the Gitea source code repository with your credentials.

This is done by create a Kubernetes `secret` to attach to the `pipeline` service account.

. Create the secret *git-secret* of type `kubernetes.io/basic-auth` with your git credentials to your Gitea source code repository:
+
[source,bash,subs="{markup-in-source}",role=execute]
----
oc create secret generic git-secret --from-literal=username=%ocp_username% --from-literal=password=%gitea_password% --type "kubernetes.io/basic-auth" -n pipeline-%guid%
----

. Annotate the secret with the URL of the git server we are using. This helps Tekton match the credentials to the correct git server:
+
[source,bash,subs="{markup-in-source}",role=execute]
----
oc annotate secret git-secret "tekton.dev/git-0=%gitea_url%" -n pipeline-%guid%
----

. Finally attach that secret to `pipeline` service account that will be used by Tekton to execute our tasks. This will allow the `git-clone` ClusterTask to access your private repo on Gitea:
+
[source,bash,subs="{markup-in-source}",role=execute]
----
oc secrets link pipeline git-secret -n pipeline-%guid%
----

. Verify that the secret has been linked:
+
[source,bash,subs="{markup-in-source}",role=execute]
----
oc describe sa pipeline -n pipeline-%guid%
----
+
.Sample Output
[source,options="nowrap",subs="{markup-in-source}"]
----
Name:                pipeline
Namespace:           pipeline-%guid%
Labels:              <none>
Annotations:         <none>
Image pull secrets:  pipeline-dockercfg-k4z7m
Mountable secrets:   pipeline-token-qhq9h
                     pipeline-dockercfg-k4z7m
                     *git-secret*
Tokens:              pipeline-token-h5jq6
                     pipeline-token-qhq9h
Events:              <none>
----

=== Enabling pipeline service account access to a other projects

The Jenkins Pipeline was able to manipulate the _dev_ and _prod_ projects because the `jenkins` service account was already setup with the correct permissions for its _dev_ and _prod_ projects.

You will do the same thing for the OpenShift pipeline, allowing the `pipeline` service account to manipulate the projects *petclinic-%guid%-dev* and *petclinic-%guid%-prod*.

. Ensure that *pipeline-%guid%* project is the active project:
+
[source,bash,subs="{markup-in-source}",role=execute]
----
oc project pipeline-%guid%
----

. Add the `edit` role in *petclinic-%guid%-dev* to all service accounts in project *pipeline-%guid%*:
+
[source,bash,subs="{markup-in-source}",role=execute]
----
oc policy add-role-to-group edit system:serviceaccounts:pipeline-%guid% -n petclinic-%guid%-dev
----

. And add the `edit` role for project *petclinic-%guid%-prod*:
+
[source,bash,subs="{markup-in-source}",role=execute]
----
oc policy add-role-to-group edit system:serviceaccounts:pipeline-%guid% -n petclinic-%guid%-prod
----

== Test tasks individually

One of the nice features of OpenShift pipelines is that you can test each task in the pipeline individually. This happens by creating a *TaskRun* that references a task, specifies the required input and output parameters and optionally specifies a workspace to persist data.

=== Test git-clone Task

First you will execute the first step of the Pipeline, the `git-clone` ClusterTask responsible of cloning our private repository.

If you analyzed the ClusterTask in the previous section, you noticed that it requires three input parameters and a workspace as output:

- *url*: URL of the git repo, use your Gitea ULR: %gitea_url%
- *revision*: branch name, we use `main`
- *deleteExisting*: removes a previous clone if present, `true` in our case

. To run a single task create a new *TaskRun* called `git-clone-taskrun`.
+
[source,bash,subs="{markup-in-source}",role=execute]
----
cat <<'EOF' | oc apply -n pipeline-%guid% -f -
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: git-clone-taskrun
spec:
  params:
  - name: url
    value: %gitea_url%
  - name: revision
    value: main
  - name: deleteExisting
    value: 'true'
  taskRef:
    kind: ClusterTask
    name: git-clone
  workspaces:
  - name: output
    persistentVolumeClaim:
      claimName: app-source-pvc
EOF
----
+
Creating the *TaskRun* immediately starts the task run.
+
NOTE: In later versions of the Tekton CLI it will be possible to create a TaskRun using the CLI also for ClusterTasks.

. Using the `tkn` command follow the log (it may take a few seconds for log messages to appear):
+
[source,bash,subs="{markup-in-source}",role=execute]
----
tkn taskrun logs -f git-clone-taskrun
----
+
.Sample Output
[source,texinfo]
----
[clone] + CHECKOUT_DIR=/workspace/output/
[clone] + '[[' true '==' true ]]
[clone] + cleandir
[clone] + '[[' -d /workspace/output/ ]]
[clone] + rm -rf '/workspace/output//*'
[clone] + rm -rf /workspace/output//.git
[clone] + rm -rf '/workspace/output//..?*'
[clone] + test -z
[clone] + test -z
[clone] + test -z
[clone] + /ko-app/git-init -url https://gitea-gitea.apps.cluster-8m5j6.8m5j6.sandbox1117.opentlc.com/wkulhane-redhat.
com/spring-petclinic -revision main -refspec  -path /workspace/output/ '-sslVerify=true' '-submodules=true' -depth 1
[clone] {"level":"info","ts":1602704036.4642532,"caller":"git/git.go:136","msg":"Successfully cloned https://gitea-gi
tea.apps.cluster-8m5j6.8m5j6.sandbox1117.opentlc.com/wkulhane-redhat.com/spring-petclinic @ 27109010a52600eb9bf227d63
1fac3f81ed6ba15 (grafted, HEAD, origin/main) in path /workspace/output/"}
[clone] {"level":"info","ts":1602704036.491851,"caller":"git/git.go:177","msg":"Successfully initialized and updated
submodules in path /workspace/output/"}
[clone] + cd /workspace/output/
[clone] + git rev-parse HEAD
[clone] + tr -d '\n'
[clone] + RESULT_SHA=27109010a52600eb9bf227d631fac3f81ed6ba15
[clone] + EXIT_CODE=0
[clone] + '[' 0 '!=' 0 ]
[clone] + echo -n 27109010a52600eb9bf227d631fac3f81ed6ba15
----
+
[TIP]
If you want to run the task again you need to either use a different name for the *TaskRun* object - or delete the previous task run before re-creating it.

=== Test maven build Task

Now execute the second task of our pipeline which builds the Spring boot app using Maven. You will use the `maven` cluster task which requires 2 parameters:

- *GOALS*: the maven goal, in this case `-DskipTests clean package` to just build the application without executing any tests.
- *MAVEN_MIRROR_URL*: the URL of an internal Nexus we can use as a Maven mirror for the app dependencies, we are going to use a Nexus Maven Mirror that is already installed on the cluster. The service URL for the Nexus Maven mirror is http://nexus.nexus.svc:8081/repository/maven-all-public. Note that because this is the URL of the OpenShift service this URL is not accessible from outside the OpenShift cluster (you really don't want to use the Route here - otherwise every request would create additional unneccessary network load).
+
[NOTE]
You will still see that some Spring artifacts are being downloaded from the internet rather than from Nexus. This is because the internal service URL for Nexus is an insecure route (`http`) and the project settings in the source code repo (`pom.xml`) require a secure connection for Spring dependencies (`nohttp`).

. Create a *TaskRun* called `maven-build-taskrun`:
+
[source,bash,subs="{markup-in-source}",role=execute]
----
cat <<'EOF' | oc apply -n pipeline-%guid% -f -
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: maven-build-taskrun
spec:
  params:
  - name: GOALS
    value:
    - -DskipTests
    - clean
    - package
  - name: MAVEN_MIRROR_URL
    value: http://nexus.nexus.svc:8081/repository/maven-all-public/
  taskRef:
    kind: ClusterTask
    name: maven
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: app-source-pvc
  - name: maven-settings
    emptyDir: {}
EOF
----

. Using the `tkn` command follow the log (it may take a few seconds for log messages to appear):
+
[source,bash,subs="{markup-in-source}",role=execute]
----
tkn taskrun logs -f maven-build-taskrun
----
+
.Sample Output
[source,texinfo]
----
...
[mvn-goals] Downloaded from mirror.default: http://nexus.nexus.svc:8081/repository/maven-all-public/org/apache/maven/maven-compat/3.0/maven-compat-3.0.jar
 (285 kB at 8.4 MB/s)
[mvn-goals] Downloaded from mirror.default: http://nexus.nexus.svc:8081/repository/maven-all-public/org/tukaani/xz/1.8/xz-1.8.jar (109 kB at 3.1 MB/s)
[mvn-goals] [INFO] Building jar: /workspace/source/target/spring-petclinic-2.3.0.BUILD-SNAPSHOT.jar
[mvn-goals] [INFO]
[mvn-goals] [INFO] --- spring-boot-maven-plugin:2.3.3.RELEASE:repackage (repackage) @ spring-petclinic ---
[mvn-goals] [INFO] Replacing main artifact with repackaged archive
[mvn-goals] [INFO] ------------------------------------------------------------------------
[mvn-goals] [INFO] BUILD SUCCESS
[mvn-goals] [INFO] ------------------------------------------------------------------------
[mvn-goals] [INFO] Total time:  07:10 min
[mvn-goals] [INFO] Finished at: 2020-10-15T13:36:17Z
[mvn-goals] [INFO] ------------------------------------------------------------------------
----
+
Once this task run is completed successfully, your app is built and ready to tested.

=== Test maven test Task

. Create a *TaskRun* called `maven-test-taskrun`:
+
[source,bash,subs="{markup-in-source}",role=execute]
----
cat <<'EOF' | oc apply -n pipeline-%guid% -f -
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: maven-test-taskrun
spec:
  params:
  - name: GOALS
    value:
    - test
  - name: MAVEN_MIRROR_URL
    value: http://nexus.nexus.svc:8081/repository/maven-all-public/
  taskRef:
    kind: ClusterTask
    name: maven
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: app-source-pvc
  - name: maven-settings
    emptyDir: {}
EOF
----

. Using the `tkn` command follow the log (it may take a few seconds for log messages to appear):
+
[source,bash,subs="{markup-in-source}",role=execute]
----
tkn taskrun logs -f maven-test-taskrun
----
+
.Sample Output
[source,texinfo]
----
...
Source       : HikariPool-1 - Shutdown completed.
[mvn-goals] 2020-10-26 12:31:57.664  INFO 212 --- [extShutdownHook] org.ehcache.core.EhcacheMana
ger          : Cache 'vets' removed from EhcacheManager.
[mvn-goals] [INFO]
[mvn-goals] [INFO] Results:
[mvn-goals] [INFO]
[mvn-goals] [WARNING] Tests run: 40, Failures: 0, Errors: 0, Skipped: 1
[mvn-goals] [INFO]
[mvn-goals] [INFO] ------------------------------------------------------------------------
[mvn-goals] [INFO] BUILD SUCCESS
[mvn-goals] [INFO] ------------------------------------------------------------------------
[mvn-goals] [INFO] Total time:  01:54 min
[mvn-goals] [INFO] Finished at: 2020-10-26T12:31:58Z
[mvn-goals] [INFO] ------------------------------------------------------------------------
----
+
Once this task run is completed successfully, your app is built and ready to be packaged into a container and pushed to OpenShift.

=== Test build-image Task

Once you app is built and tested, it's time to merge it inside a container, and this comes easy using the Source-to-Image (S2I) Task `s2i-java-11-binary-namespace` we created in previous chapter.

NOTE: A Task definition is available by default only in the project where it has been created, while a ClusterTask it's available for all projects. 

Let's look at required parameters for this Task:

- *TLSVERIFY*: it verifies if the target registry has trusted certs, default to `false` 
- *OUTPUT_IMAGE_STREAM*: the name of the ImageStream as representing the container image built in this step, format is `name`:`tag`
- *NAMESPACE*: target project where to push the result container image

At this step, we want to create a container image from latest successful build and push it to the Dev environment, ready to be deployed.

. Use `tkn` cli to create automatically a TaskRun and start our Task:
+
[source,bash,subs="{markup-in-source}",role=execute]
----
tkn task start s2i-java-11-binary-namespace  \
    -p TLSVERIFY=false  \
    -p OUTPUT_IMAGE_STREAM=petclinic:latest  \
    -p NAMESPACE=petclinic-%guid%-dev \
    -w name=source,claimName=app-source-pvc \
    --showlog \
    -n pipeline-%guid%
----
+
.Sample Output
[source,texinfo]
----
...
[build] test-classes/org/springframework/samples/petclinic/vet/
[build] test-classes/org/springframework/samples/petclinic/vet/VetControllerTests.class
[build] test-classes/org/springframework/samples/petclinic/vet/VetTests.class
[build] --> 06dcb1ff43b
[build] STEP 8: CMD /usr/local/s2i/run
[build] STEP 9: COMMIT image-registry.openshift-image-registry.svc:5000/petclinic-nvin-dev/petcl
inic:latest
[build] --> 75d21fa3235
[build] 75d21fa32350c916b7c9b48d0f1d4c50f471a0ef47f0decbf173cf04c0e0b670

[push] Getting image source signatures
[push] Copying blob sha256:d5409e07a0c879144c196c38ab9a7a3f59d8630882ad19d2d87e0aaa7af09c7f
[push] Copying blob sha256:548d9305d034bf3372b997ad14f69bd608eea7112a6200daebf92ed91cb52dfc
[push] Copying blob sha256:542fb4667c977c3105e17701368e9ce44f4cc331b9b34ec9aabd04d6f93761e8
[push] Copying blob sha256:c13e1fc2ca26f7749d5a2913f891616b909915f1e900be49c24b17f2faaa6f04
[push] Copying blob sha256:245644d3cbb3f32769c9667fe3159a0f56d4190d7f74dd3c7518b6c7f4c05050
[push] Copying blob sha256:14324321c32b5060c4aa3d4c6dc03aa49db935df5bde16deb39ec7ef12b354a0
[push] Copying config sha256:75d21fa32350c916b7c9b48d0f1d4c50f471a0ef47f0decbf173cf04c0e0b670
[push] Writing manifest to image destination
[push] Copying config sha256:75d21fa32350c916b7c9b48d0f1d4c50f471a0ef47f0decbf173cf04c0e0b670
[push] Writing manifest to image destination
[push] Storing signatures
----


=== Test deploy-to-dev Task

Now that the container image is available in our petclinic-%guid%-dev project representing the Dev environment, we are ready to deploy it with the `deploy-to-project` Task we already created.

Let's look at required parameters for this Task:

- *DEPLOYMENT*: the name of the Deployment to use for our app 
- *IMAGE_STREAM*: the name of the ImageStream as representing the container image pushed to the target project
- *NAMESPACE*: target project where to deploy the container image

Let's deploy our app to Dev project `petclinic-%guid%-dev`:

. Use `tkn` cli to create automatically a TaskRun and start our Task:
+
[source,bash,subs="{markup-in-source}",role=execute]
----
tkn task start deploy-to-project  \
    -p DEPLOYMENT=petclinic  \
    -p IMAGE_STREAM=petclinic:latest  \
    -p NAMESPACE=petclinic-%guid%-dev \
    --showlog \
    -n pipeline-%guid%
----
+
NOTE: From this point of the pipeline, the workspace is not needed anymore, since the container image has been already stored in the Container Registry and we can manage it via ImageStreams and Deployments
+
.Sample Output
[source,texinfo]
----
[deploy] + image_ref=image-registry.openshift-image-registry.svc:5000/petclinic-nvin-dev/petclin
ic:latest
[deploy] + echo 'Deploying image-registry.openshift-image-registry.svc:5000/petclinic-nvin-dev/p
etclinic:latest'
[deploy] Deploying image-registry.openshift-image-registry.svc:5000/petclinic-nvin-dev/petclinic
:latest
[deploy] ++ oc get deployment petclinic -n petclinic-nvin-dev
[deploy] + deployment='NAME        READY   UP-TO-DATE   AVAILABLE   AGE
[deploy] petclinic   1/1     1            1           12d'
[deploy] + '[' 0 -ne 0 ']'
[deploy] + oc set image deployment/petclinic petclinic=image-registry.openshift-image-registry.s
vc:5000/petclinic-nvin-dev/petclinic:latest -n petclinic-nvin-dev
[deploy] deployment.apps/petclinic image updated
[deploy] ++ date +%s
[deploy] + oc patch deployment petclinic -p '{"spec": {"template": {"metadata": { "labels": {  "
redeploy": "1603715966"}}}}}' -n petclinic-nvin-dev
[deploy] deployment.apps/petclinic patched
[deploy] + oc rollout status deployment/petclinic -n petclinic-nvin-dev
[deploy] Waiting for deployment spec update to be observed...
[deploy] Waiting for deployment "petclinic" rollout to finish: 0 out of 1 new replicas have been
 updated...
[deploy] Waiting for deployment "petclinic" rollout to finish: 0 out of 1 new replicas have been
 updated...
[deploy] Waiting for deployment "petclinic" rollout to finish: 0 out of 1 new replicas have been
 updated...
[deploy] Waiting for deployment "petclinic" rollout to finish: 1 old replicas are pending termin
ation...
[deploy] Waiting for deployment "petclinic" rollout to finish: 1 old replicas are pending termin
ation...
[deploy] deployment "petclinic" successfully rolled out
----

=== Test promote-to-prod Task

If we verified that our app is running fine for the Dev environment, we can decide to promote it to the Prod environment, represented by `petclinic-%guid%-prod` project.

Let's look at required parameters for this Task:

- *DEPLOYMENT*: the name of the Deployment to use for our app 
- *IMAGE_STREAM*: the name of the ImageStream as representing the container image pushed to the target project
- *DEV_NAMESPACE*: source project from where to promote the app the container image
- *PROD_NAMESPACE*: target project to promote the app by tagging the container image (`oc tag`)

Let's promote our app from Dev project `petclinic-%guid%-dev` to Prod project `petclinic-%guid%-prod` by tagging the ImageStream from `petclinic:latest` to `petclinic:prod`. This will be the image tag used for the Prod environment.  

. Use `tkn` cli to create automatically a TaskRun and start our Task:
+
[source,bash,subs="{markup-in-source}",role=execute]
----
tkn task start promote-to-prod  \
    -p DEPLOYMENT=petclinic  \
    -p IMAGE_STREAM=petclinic:latest  \
    -p DEV_NAMESPACE=petclinic-%guid%-dev \
    -p PROD_NAMESPACE=petclinic-%guid%-prod \
    --showlog \
    -n pipeline-%guid%
----
+
.Sample Output
[source,texinfo]
----
[deploy] + oc tag petclinic-nvin-dev/petclinic:latest petclinic-nvin-dev/petclinic:prod
[deploy] Tag petclinic-nvin-dev/petclinic:prod set to petclinic-nvin-dev/petclinic@sha256:67ad1c
50ee57742ecae24d4aadfcf24a84c23a14f1ade6b921282ce289720080.
----

=== Test deploy-to-prod Task

Finally we are ready for the last step, the deployment of the app for Production!

We can reuse the same Task `deploy-to-project` as before, changing the parameters to deploy the app to `petclinic-%guid%-prod` project and to use `petclinc:prod` tag at this time:

. Use `tkn` cli to create automatically a TaskRun and start our Task:
+
[source,bash,subs="{markup-in-source}",role=execute]
----
tkn task start deploy-to-project  \
    -p DEPLOYMENT=petclinic  \
    -p IMAGE_STREAM=petclinic:prod  \
    -p NAMESPACE=petclinic-%guid%-prod \
    --showlog \
    -n pipeline-%guid%
----
+
.Sample Output
[source,texinfo]
----
[deploy] + image_ref=image-registry.openshift-image-registry.svc:5000/petclinic-nvin-prod/petcli
nic:prod
[deploy] + echo 'Deploying image-registry.openshift-image-registry.svc:5000/petclinic-nvin-prod/
petclinic:prod'
[deploy] Deploying image-registry.openshift-image-registry.svc:5000/petclinic-nvin-prod/petclini
c:prod
[deploy] ++ oc get deployment petclinic -n petclinic-nvin-prod
[deploy] + deployment='NAME        READY   UP-TO-DATE   AVAILABLE   AGE
[deploy] petclinic   1/1     1            1           12d'
[deploy] + '[' 0 -ne 0 ']'
[deploy] + oc set image deployment/petclinic petclinic=image-registry.openshift-image-registry.s
vc:5000/petclinic-nvin-prod/petclinic:prod -n petclinic-nvin-prod
[deploy] deployment.apps/petclinic image updated
[deploy] ++ date +%s
[deploy] + oc patch deployment petclinic -p '{"spec": {"template": {"metadata": { "labels": {  "
redeploy": "1603716255"}}}}}' -n petclinic-nvin-prod
[deploy] deployment.apps/petclinic patched
[deploy] + oc rollout status deployment/petclinic -n petclinic-nvin-prod
[deploy] Waiting for deployment spec update to be observed...
[deploy] Waiting for deployment "petclinic" rollout to finish: 0 out of 1 new replicas have been
 updated...
[deploy] Waiting for deployment "petclinic" rollout to finish: 0 out of 1 new replicas have been
 updated...
[deploy] Waiting for deployment "petclinic" rollout to finish: 0 out of 1 new replicas have been
 updated...
[deploy] Waiting for deployment "petclinic" rollout to finish: 1 old replicas are pending termin
ation...
[deploy] Waiting for deployment "petclinic" rollout to finish: 1 old replicas are pending termin
ation...
[deploy] deployment "petclinic" successfully rolled out
----

== Summary

In general, if you want to test each task, what you need to do is:

- Create a TaskRun with YAML or tkn cli
- Add all required input and output parameters
- If required ensure the Workspace (PersistentVolumeClaim) is present

At this point you are ready to pack all tasks and manage them into a single `Pipeline`. Pipelines contains a list of Task and ClusterTask, and all pipeline parameters are passed to tasks in the form of `$(params.PARAM_NAME)`.
