:markup-in-source: verbatim,attributes,quotes

// Title comes from the workshop.yaml
// == User Information

Feel free to resize the panes in this window to make more room for the lab instructions.

'''

Here is some important information about your environment:

* Your GUID is: *%guid%*
* Your OpenShift and Gitea username is: *%ocp_username%* (which is your OpenTLC user ID)
* Your OpenShift password is your OpenTLC Password
* Your Gitea password is %gitea_password%

'''

* To log into OpenShift use the following command: *%login_command%*
* OpenShift Web Console URL: *%web_console_url%*

'''

* Jenkins: %jenkins_url%
* Gitea: %gitea_url%
// * Nexus: %nexus_url%
// * ArgoCD: %argocd_url%

'''

* The following projects have been created for you (you do not have permission to create your own projects):
** *bookbag-%guid%*: The project that runs the lab instructions and terminal for you to use during the lab
** *jenkins-%guid%*: Jenkins Project with a running Jenkins and an OpenShift build configuration of type `JenkinsPipeline` that holds the Jenkins Pipeline that you will translate into an OpenShift pipeline
** *petclinic-jenkins-%guid%-dev*: Development Project to be used by Jenkins
** *petclinic-jenkins-%guid%-prod*: Production Project to be used by Jenkins
** *pipeline-%guid%*: A project to hold the resources that will make up your OpenShift pipeline
** *petclinic-%guid%-dev*: Development Project to be used by your OpenShift pipeline
** *petclinic-%guid%-prod*: Production Project to be used by your OpenShift pipeline

== Log into OpenShift

For the labs to work you need to log into OpenShift in the terminal to the right using your OpenTLC ID. You can click the command below if you don't feel like typing it. But regardless you will need to provide your OpenTLC password.

[source,bash,subs="{markup-in-source}",role=execute]
----
%login_command% --insecure-skip-tls-verify=true
----

.Sample Output
[source,options="nowrap",subs="{markup-in-source}"]
----
Authentication required for https://api.cluster-wkrhtr.red.osp.opentlc.com:6443 (openshift)
Username: wkulhane-redhat.com
Password:
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * bookbag-wk
    jenkins-wk
    petclinic-jenkins-wk-dev
    petclinic-jenkins-wk-prod
    petclinic-wk-dev
    petclinic-wk-prod
    pipeline-wk

Using project "bookbag-wk".
----

[TIP]
You can always come back to this page if you need a reminder of any of your lab information. But once you have logged into OpenShift the rest of the lab instructions should have the correct values.
