---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: petclinic
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        labels:
          tekton.dev/pipeline: petclinic-pipeline
        name: petclinic-deploy-$(uid)
      spec:
        params:
          - name: APP_NAME
            value: petclinic
          - name: APP_GIT_URL
            value: $(params.git-repo-url)
          - name: APP_GIT_REVISION
            value: $(params.git-revision)
        pipelineRef:
          name: petclinic-pipeline
        workspaces:
        - name: app-source
          persistentVolumeClaim:
            claimName: app-source-pvc
        - name: maven-settings
          emptyDir: {}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: petclinic
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.clone_url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.after)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: petclinic
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: petclinic
    template:
      name: petclinic
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: petclinic
  name: el-petclinic
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-petclinic
    weight: 100
